### ISSUE TITLE
add pygaul to the gee-community org

### ISSUE THREAD

**Issue by 12rambau** [gee-community/github-administration#3]
As part of my job at FAO, I designed several tools in the open-foris org. I'm starting to extract some of them from the main sepal-ui repository as I think they could make sense for other earthengine-python-api users. 

This python package is giving the user super easy access to the FAO GAUL dataset to create a feature collection from it with as few parameter as possible, namely: 
- the name of the admin 
- the content level requested. 

- The python package: https://pypi.org/project/pygaul/
- The documentation: https://pygaul.readthedocs.io/en/latest/
- the code: https://github.com/12rambau/pygaul

Let me know what you think

**Comment by giswqs** [comment]
That looks go to me. I have invited you as a member as of org. You can start transfering the repo.

**Comment by 12rambau** [comment]
thanks I moved the repository to the organization, can you grant me admin rights on the pygaul repo so that I can still modify parameters like github actions secrets ?

**Comment by giswqs** [comment]
Done.
