### ISSUE TITLE
pin github administration repository

### ISSUE THREAD

**Issue by 12rambau** [gee-community/github-administration#4]
I was crowling in the repositories of the community and I discovered multiple ones that could have act as a github administration. 
Would it be possible to pin this one at the top so it's always visible to community members and visitors and delete the duplicates ? 

I specificcally think about: 
- https://github.com/[gee-community/gee-community.github.io](https://github.com/gee-community/gee-community.github.io)
- https://github.com/gee-community/ee-community

Both of them are mainly empty (a license and a readme) and never been active for several years.

**Comment by giswqs** [comment]
One alternative is to delete this repo and move adminstration to [gee-community.github.io](https://github.com/gee-community/gee-community.github.io). The pin discussion can be then linked to [gee-community.github.io](https://github.com/gee-community/gee-community.github.io)

**Comment by 12rambau** [comment]
I don't think it's useful to have 2 places with all the info so yes I would be in favor of keeping only gee-community.github.io in this case

**Comment by giswqs** [comment]
It has been moved. Deleting this repo now.
